name: promotion_overlay_platform_interface
description: A common platform interface for the promotion_overlay plugin.
repository: https://github.com/psycatgames/promotion_overlay_platform_interface
version: 1.0.1

environment:
  sdk: ">=2.17.1 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

topics:
  - app-store